//
//  RecommendationPanel.swift
//  Reading Tracker
//
//  Created by Johan Rembeci on 6/28/26.
//


//
//  RecommendationPanel.swift
//  Reading Tracker
//
//  Shows a ranked "What to Read Next" list generated by
//  PredictiveRecommendationEngineV3. Each recommendation includes a score
//  breakdown so the user understands why a book was surfaced.
//
//  Engine called (read-only, deterministic, no side effects):
//    - PredictiveRecommendationEngineV3().recommend(books:context:)
//

import SwiftUI

struct RecommendationPanel: View {

    @EnvironmentObject private var dataStore: DataStore
    @Environment(\.dismiss) private var dismiss

    @State private var result:     RecommendationResultV3?
    @State private var isLoading:  Bool = true
    @State private var expanded:   UUID?   // which card is showing the breakdown

    var body: some View {
        NavigationStack {
            Group {
                if isLoading {
                    ProgressView("Ranking your library…")
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else if dataStore.books.isEmpty {
                    emptyLibraryState
                } else if let result, !result.topBooks.isEmpty {
                    content(result: result)
                } else {
                    notEnoughDataState
                }
            }
            .navigationTitle("What to Read Next")
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                }

                ToolbarItem(placement: .secondaryAction) {
                    Button {
                        Task { await runRecommendation() }
                    } label: {
                        Label("Refresh", systemImage: "arrow.clockwise")
                    }
                }
            }
        }
        .frame(minWidth: 480, minHeight: 540)
        .task { await runRecommendation() }
    }

    // MARK: - Content

    private func content(result: RecommendationResultV3) -> some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {

                // Engine message
                if !result.message.isEmpty {
                    Text(result.message)
                        .font(.subheadline)
                        .foregroundColor(.secondary)
                        .padding(12)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .background(Color.secondary.opacity(0.07),
                                    in: RoundedRectangle(cornerRadius: 10))
                }

                // Ranked book cards
                ForEach(Array(result.topBooks.prefix(7).enumerated()), id: \.element.id) { rank, scored in
                    RecommendationCard(
                        rank:        rank + 1,
                        scored:      scored,
                        book:        dataStore.books.first { $0.id == scored.bookID },
                        isExpanded:  expanded == scored.id,
                        onToggle:    { expanded = (expanded == scored.id) ? nil : scored.id }
                    )
                }
            }
            .padding(24)
        }
    }

    // MARK: - States

    private var emptyLibraryState: some View {
        ContentUnavailableView(
            "No Books Yet",
            systemImage: "books.vertical",
            description: Text("Import some books to get personalised reading recommendations.")
        )
    }

    private var notEnoughDataState: some View {
        ContentUnavailableView(
            "Not Enough Data",
            systemImage: "chart.bar.xaxis",
            description: Text("Read a few more sessions so the recommendation engine can learn your preferences.")
        )
    }

    // MARK: - Engine Call

    @MainActor
    private func runRecommendation() async {
        isLoading = true
        // Recommendation is CPU-only (no I/O). Yield to let the loading
        // indicator render, then run the computation.
        await Task.yield()
        let engine = PredictiveRecommendationEngineV3()
        result     = engine.recommend(books: dataStore.books, context: Date())
        isLoading  = false
    }
}

// MARK: - RecommendationCard

private struct RecommendationCard: View {
    let rank:       Int
    let scored:     BookRecommendationScoreV3
    let book:       Book?
    let isExpanded: Bool
    let onToggle:   () -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {

            // Main row
            Button(action: onToggle) {
                HStack(spacing: 14) {
                    // Rank badge
                    ZStack {
                        Circle()
                            .fill(rankColor.opacity(0.15))
                        Text("\(rank)")
                            .font(.headline)
                            .fontWeight(.bold)
                            .foregroundColor(rankColor)
                    }
                    .frame(width: 38, height: 38)

                    // Book info
                    VStack(alignment: .leading, spacing: 3) {
                        Text(scored.title)
                            .font(.subheadline)
                            .fontWeight(.semibold)
                            .lineLimit(1)
                        if let author = book?.author {
                            Text(author)
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                    }

                    Spacer()

                    // Score gauge
                    ScoreGauge(score: scored.totalScore)

                    Image(systemName: isExpanded ? "chevron.up" : "chevron.down")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                .padding(14)
            }
            .buttonStyle(.plain)

            // Expandable score breakdown
            if isExpanded {
                Divider().padding(.horizontal, 14)
                BreakdownGrid(scored: scored, book: book)
                    .padding(14)
                    .transition(.opacity.combined(with: .move(edge: .top)))
            }
        }
        .background(Color.secondary.opacity(0.06), in: RoundedRectangle(cornerRadius: 12))
        .animation(.easeInOut(duration: 0.2), value: isExpanded)
    }

    private var rankColor: Color {
        switch rank {
        case 1:  return .yellow
        case 2:  return Color(red: 0.75, green: 0.75, blue: 0.80)
        case 3:  return Color(red: 0.80, green: 0.50, blue: 0.20)
        default: return .accentColor
        }
    }
}

// MARK: - ScoreGauge

private struct ScoreGauge: View {
    let score: Double   // 0…1

    var body: some View {
        HStack(spacing: 4) {
            // 5-segment bar
            ForEach(0..<5, id: \.self) { i in
                RoundedRectangle(cornerRadius: 2)
                    .fill(Double(i + 1) <= score * 5
                          ? Color.accentColor
                          : Color.secondary.opacity(0.2))
                    .frame(width: 6, height: 16)
            }
            Text(String(format: "%.2f", score))
                .font(.caption2)
                .foregroundColor(.secondary)
                .frame(width: 30, alignment: .trailing)
        }
    }
}

// MARK: - BreakdownGrid

private struct BreakdownGrid: View {
    let scored: BookRecommendationScoreV3
    let book:   Book?

    // Parse the engine's own breakdown string into labelled rows.
    private var rows: [(label: String, value: Double)] {
        [
            ("Time fit",       scored.timeFitScore),
            ("Genre affinity", scored.genreAffinityScore),
            ("Engagement",     scored.engagementScore),
            ("Completion",     scored.completionProbability),
            ("Difficulty fit", scored.difficultyFitScore),
            ("Momentum",       scored.momentumBoost),
            ("Novelty",        scored.noveltyScore),
        ]
    }

    var body: some View {
        VStack(spacing: 6) {
            ForEach(rows, id: \.label) { row in
                HStack {
                    Text(row.label)
                        .font(.caption)
                        .foregroundColor(.secondary)
                        .frame(width: 110, alignment: .leading)

                    GeometryReader { geo in
                        ZStack(alignment: .leading) {
                            RoundedRectangle(cornerRadius: 3)
                                .fill(Color.secondary.opacity(0.12))
                            RoundedRectangle(cornerRadius: 3)
                                .fill(Color.accentColor.opacity(0.7))
                                .frame(width: geo.size.width * CGFloat(row.value.clamped(to: 0...1)))
                        }
                    }
                    .frame(height: 6)

                    Text(String(format: "%.2f", row.value))
                        .font(.caption2)
                        .foregroundColor(.secondary)
                        .frame(width: 32, alignment: .trailing)
                }
            }

            if let book, book.currentPage > 0 {
                Divider().padding(.vertical, 4)
                HStack {
                    Text("Currently on page \(book.currentPage) of \(book.totalPages)")
                        .font(.caption)
                        .foregroundColor(.secondary)
                    Spacer()
                    Text("\(Int(Double(book.currentPage) / Double(max(book.totalPages, 1)) * 100))% complete")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }
        }
    }
}

// MARK: - Preview

#Preview {
    RecommendationPanel()
        .environmentObject(DataStore())
}